### ISSUE TITLE
No acknowledgement given for normal ticket registrations for main conference

### ISSUE THREAD

**Issue by tsuresh** [gdgsrilanka/techevents-portal#24]
Once I register for normal tickets, it doesn't give any acknowledgement saying that I've registered and await for selection status.

![FireShot Capture 832 - DevFest Sri Lanka 2023_ Main Conference - Tech Events - dev techevents lk](https://github.com/gdgsrilanka/techevents-portal/assets/3047253/f59c062c-462d-4a9f-90ea-92858dc11112)

**Comment by miyurugunarathna** [comment]
Fixed
