### ISSUE TITLE
Form validations for event registrations

### ISSUE THREAD

**Issue by tsuresh** [gdgsrilanka/techevents-portal#25]
Forms can be submitted without even having answers in the fields.

Please apply validation.

![FireShot Capture 834 - DevFest Sri Lanka 2023_ CodeLabs - Tech Events - dev techevents lk](https://github.com/gdgsrilanka/techevents-portal/assets/3047253/3a944950-60af-44c6-bc50-ee013be4038b)

**Comment by miyurugunarathna** [comment]
Fixed
